name: ci 
on:
  workflow_dispatch: 
  push: 
    branches:
    - main
    # paths-ignore:
    #   - '.github/workflows/**'
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: andrezitodev:${{ github.run_number }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
